"use strict";

const { summarizeError } = require('../util/logger');

function formatDuration(ms) {
    if (!ms || ms <= 0) return '-';
    const totalSeconds = Math.floor(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

function getArtistDisplay(artist) {
    if (!artist) return '未知';
    if (Array.isArray(artist)) {
        return artist.map(a => a.name || a).join(', ');
    }
    return artist;
}

function renderSongListMarkdownTable(songList, config = {}) {
    if (!songList || !Array.isArray(songList) || songList.length === 0) {
        return '';
    }

    const maxDisplay = config.maxDisplay || 10;
    const displayList = songList.slice(0, maxDisplay);
    const waitTimeout = config.waitTimeout || 45;
    const atRobotText = config.atRobotText || "@机器人";
    const exitCommands = config.exitCommand ? config.exitCommand.split(/[,，]/).map(cmd => cmd.trim()) : ['0', '不听了'];
    const exitCommandForLink = exitCommands[0] || '0';
    const showExitTip = config.menuExitCommandTip !== false;
    const useSongInlineCommandLink = config.useSongInlineCommandLink !== false;
    const useExitInlineCommandLink = config.useExitInlineCommandLink !== false;
    const markdownTitle = config.markdownTitle || '🎵 歌单列表';
    const markdownSummary = config.markdownSummary || `📋 共 ${songList.length} 首歌曲，显示前 ${maxDisplay} 首`;
    const waitTime = config.waitTime || `⏰ 请在${waitTimeout}秒内，\n输入歌曲对应的序号:\n➣示例：${atRobotText} 1`;
    const waitTimeInline = config.waitTimeInline || `⏰ 请在 ${waitTimeout} 秒内，\n点击对应的蓝字发送，或直接输入歌曲对应的序号\n➣示例：${atRobotText} 1`;
    const exitCommandTipMarkdownInlinePrefix = config.exitCommandTipMarkdownInlinePrefix || '退出选择请点';
    const exitCommandTipMarkdownInlineSuffix = config.exitCommandTipMarkdownInlineSuffix || '或者发送其中的任意内容';
    const exitCommandTipMarkdownText = config.exitCommandTipMarkdownText || `退出选择请发 @机器人 + 【${exitCommands.join(' / ')}】 中的任意内容`;

    let md = `# ${markdownTitle}\n\n`;

    // 添加渲染信息（如果启用）
    if (config.showRenderInfo) {
        const version = config.version || 'unknown';
        const repositoryUrl = config.repositoryUrl || '';
        const dateTime = new Date().toISOString();
        
        md += `> generated by koishi plugin: music-link-vincentzyu-fork\n`;
        md += `> version: ${version}\n`;
        md += `> date_time: ${dateTime}\n`;
        if (repositoryUrl) {
            md += `> repo_url: ${repositoryUrl}\n`;
        }
        md += `\n`;
    }

    md += `| # | 歌曲名称 | 歌手 | 时长 |\n`;
    md += `|---|---------|------|-----|\n`;

    displayList.forEach((song, index) => {
        const name = song.name || song.song || '未知';
        const artist = song.artists || song.artist || song.ar || song.singer || '未知';
        const duration = formatDuration(song.duration);

        const displayName = useSongInlineCommandLink
            ? `[${name}](mqqapi://aio/%69nlinecmd?command=${index + 1}&enter=true)`
            : name;

        md += `| ${index + 1} | ${displayName} | ${getArtistDisplay(artist)} | ${duration} |\n`;
    });

    md += `> ${markdownSummary}\n\n`;


    md += `\n---\n\n`;
    if (showExitTip) {
        if (useExitInlineCommandLink) {
            md += `#### ${exitCommandTipMarkdownInlinePrefix} [【${exitCommands.join(' / ')}】](mqqapi://aio/%69nlinecmd?command=${encodeURIComponent(exitCommandForLink)}&enter=true)\n\n${exitCommandTipMarkdownInlineSuffix}\n\n`;
        } else {
            md += `#### ${exitCommandTipMarkdownText}\n\n`;
        }
    }
    if (useSongInlineCommandLink) {
        md += `> ${waitTimeInline.replace(/\n/g, '\n> ')}\n`;
    } else {
        md += `> ${waitTime.replace(/\n/g, '\n> ')}\n`;
    }

    return md;
}

function renderSongListMarkdownStyle(songList, config = {}) {
    if (!songList || !Array.isArray(songList) || songList.length === 0) {
        return '';
    }

    const maxDisplay = config.maxDisplay || 10;
    const displayList = songList.slice(0, maxDisplay);
    const waitTimeout = config.waitTimeout || 45;
    const atRobotText = config.atRobotText || "@机器人";
    const exitCommands = config.exitCommand ? config.exitCommand.split(/[,，]/).map(cmd => cmd.trim()) : ['0', '不听了'];
    const exitCommandForLink = exitCommands[0] || '0';
    const showExitTip = config.menuExitCommandTip !== false;
    const useSongInlineCommandLink = config.useSongInlineCommandLink !== false;
    const useExitInlineCommandLink = config.useExitInlineCommandLink !== false;
    const markdownTitle = config.markdownTitle || '🎵 歌单列表';
    const markdownSummary = config.markdownSummary || `📋 共 ${songList.length} 首歌曲，显示前 ${maxDisplay} 首`;
    const waitTime = config.waitTime || `⏰ 请在${waitTimeout}秒内，\n输入歌曲对应的序号:\n➣示例：${atRobotText} 1`;
    const waitTimeInline = config.waitTimeInline || `⏰ 请在 ${waitTimeout} 秒内，\n点击对应的蓝字发送，或直接输入歌曲对应的序号\n➣示例：${atRobotText} 1`;
    const exitCommandTipMarkdownInlinePrefix = config.exitCommandTipMarkdownInlinePrefix || '退出选择请点';
    const exitCommandTipMarkdownInlineSuffix = config.exitCommandTipMarkdownInlineSuffix || '或者发送其中的任意内容';
    const exitCommandTipMarkdownText = config.exitCommandTipMarkdownText || `退出选择请发 @机器人 + 【${exitCommands.join(' / ')}】 中的任意内容`;

    let md = `# ${markdownTitle}\n\n`;

    // 添加渲染信息（如果启用）
    if (config.showRenderInfo) {
        const version = config.version || 'unknown';
        const repositoryUrl = config.repositoryUrl || '';
        const dateTime = new Date().toISOString();
        
        md += `> generated by koishi plugin: music-link-vincentzyu-fork\n`;
        md += `> version: ${version}\n`;
        md += `> date_time: ${dateTime}\n`;
        if (repositoryUrl) {
            md += `> repo_url: ${repositoryUrl}\n`;
        }
        md += `\n`;
    }

    displayList.forEach((song, index) => {
        const name = song.name || song.song || '未知';
        const artist = song.artists || song.artist || song.ar || song.singer || '未知';
        const duration = formatDuration(song.duration);

        if (useSongInlineCommandLink) {
            md += `#### [${index + 1}. ${name}](mqqapi://aio/%69nlinecmd?command=${index + 1}&enter=true)\n`;
        } else {
            md += `#### ${index + 1}. ${name}\n`;
        }
        md += `> ⏱️ **时长**: ${duration} | 👤 **歌手**: ${getArtistDisplay(artist)}\n\n`;
    });

    md += `> ${markdownSummary}\n\n`;

    md += `---\n\n`;
    if (showExitTip) {
        if (useExitInlineCommandLink) {
            md += `#### ${exitCommandTipMarkdownInlinePrefix} [【${exitCommands.join(' / ')}】](mqqapi://aio/%69nlinecmd?command=${encodeURIComponent(exitCommandForLink)}&enter=true)\n\n${exitCommandTipMarkdownInlineSuffix}\n\n`;
        } else {
            md += `#### ${exitCommandTipMarkdownText}\n\n`;
        }
    }
    if (useSongInlineCommandLink) {
        md += `> ${waitTimeInline.replace(/\n/g, '\n> ')}\n`;
    } else {
        md += `> ${waitTime.replace(/\n/g, '\n> ')}\n`;
    }

    return md;
}

async function sendQQMarkdown(_ctx, session, content, musicLogger) {
    try {
        await session.bot.internal.sendMessage(session.channelId, {
            msg_id: session.messageId,
            msg_type: 2,
            markdown: {
                content: content
            }
        });
        return true;
    } catch (error) {
        musicLogger?.logInfo('⚠️ QQ Markdown 发送失败', summarizeError(error));
        musicLogger?.logDebug('QQ Markdown 发送异常', error);
        return false;
    }
}

module.exports = {
    renderSongListMarkdownTable,
    renderSongListMarkdownStyle,
    sendQQMarkdown
};
